---
# Copyright 2016, 2017 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file describes the configuration for a Swift cluster that
# hosts the account, container, and object rings on the same set
# of hosts.
#
# It features three controller nodes, Swift proxy nodes,
# Swift object nodes.

version: 1.1

reference-architecture:
    - swift

ipaddr-mgmt-network: 192.168.16.0/24
ipaddr-mgmt-client-network: 192.168.20.0/24
vlan-mgmt-network: 16
vlan-mgmt-client-network: 20
port-mgmt-network: 46
port-mgmt-data-network:
    rack1:
        - 45
        - 47
ipaddr-mgmt-switch:
    rack1: 192.168.16.20
ipaddr-data-switch:
    rack1:
        - 192.168.16.25
        - 192.168.16.30
ipaddr-mlag-vip:
    _rack1: 192.168.16.254
cidr-mlag-ipl:
    _rack1:
        - 10.0.0.1/24
        - 10.0.0.2/24
mlag-vlan:
    _rack1: 4000
mlag-port-channel:
    _rack1: 35
mlag-ipl-ports:
    _rack1:
        -
            - 37
            - 38
        -
            - 37
            - 38
redundant-network: true
userid-default: ubuntu
password-default: passw0rd
userid-mgmt-switch: admin    # applies to all mgmt switches
password-mgmt-switch: admin  # applies to all mgmt switches
userid-data-switch: admin
password-data-switch: admin
internal-floating-ipaddr: 172.29.236.50
external-floating-ipaddr: 10.0.16.50
networks:
    ext1:
        description: Interface for eth10
        method: manual
        eth-port: eth10
        mtu: 9000
    ext2:
        description: Interface for eth11
        method: manual
        eth-port: eth11
        mtu: 9000
    ext3:
        description: Interface for eth12
        method: manual
        eth-port: eth12
        mtu: 9000
    ext4:
        description: Interface for eth13
        method: manual
        eth-port: eth13
        mtu: 9000
    pxe-dhcp:
        description: Change pxe port(eth15) to dhcp
        method: dhcp
        eth-port: eth15
    external1:
        description: bonded public interface
        bond: osbond0
        addr: 10.0.16.0/22
        # Note you can uncomment the following section to provide a set of IPs
        # on this network that will be allocated to the hosts.  The default
        # behavior is to allocate from the full subnet.
        #available-ips:
        #    - 10.0.16.20
        #    - 10.0.16.35
        #    - 10.0.16.106 10.0.16.110  # this is an IP range
        #    - 10.0.16.115
        broadcast: 10.0.19.255
        gateway: 10.0.16.1
        #dns-nameservers: 10.0.16.200
        #dns-search: mycompany.domain.com
        method: static
        bond-interfaces:
            - eth10
            - eth11
        mtu: 9000
        bond-primary: eth10
        bond-mode: 4
        optional-bond-arguments:
            bond-miimon: 100
            bond-lacp-rate: 1
    external2:
        description: bonded interface
        bond: osbond1
        method: manual
        bond-interfaces:
        # for full protection against failure, eth12 and eth13 should come from different NICs
            - eth12
            - eth13
        mtu: 9000
        bond-primary: eth12
        bond-mode: 4
        optional-bond-arguments:
            bond-miimon: 100
            bond-lacp-rate: 1
    openstack-mgmt:
        description: OpenStack Management Network
        bridge: br-mgmt
        method: static
        tcp_segmentation_offload: 'off'
        addr: 172.29.236.0/22
        vlan: 10
        eth-port: osbond0
        mtu: 9000
    openstack-stg:
        description: OpenStack Storage Network
        bridge: br-storage
        method: static
        tcp_segmentation_offload: 'off'
        addr: 172.29.244.0/22
        vlan: 20
        eth-port: osbond0
        mtu: 9000
    swift-replication:
        description: Swift Replication Network
        addr: 172.29.248.0/22
        bridge: br-swift-repl
        method: static
        vlan: 30
        eth-port: osbond1
        mtu: 9000
racks:
    - rack-id: rack1
      data-center: dataeast
      room: room101
      row: row1
node-templates:
    controllers:
        hostname: controller
        roles:
            - solution_keys
            - solution_inventory
        userid-ipmi: admin
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
            mac-eth12: eth12
            mac-eth13: eth13
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 1
                    - 2
                    - 3
            ipmi:
                rack1:
                    - 4
                    - 5
                    - 6
            eth10:       # for MLAG setup, these connect to 1st data switch
                rack1:
                    - 1
                    - 2
                    - 3
            eth11:       # for MLAG setup, these connect to 2nd data switch
                rack1:
                    - 1
                    - 2
                    - 3
            eth12:       # for MLAG setup, these connect to 1st data switch
                rack1:
                    - 4
                    - 5
                    - 6
            eth13:       # for MLAG setup, these connect to 2nd data switch
                rack1:
                    - 4
                    - 5
                    - 6
        networks:
            - ext1
            - ext2
            - ext3
            - ext4
            - external1
            - external2
            - openstack-mgmt
            - openstack-stg
            - pxe-dhcp
    swift-object:
        hostname: swiftobject
        userid-ipmi: admin
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
            mac-eth12: eth12
            mac-eth13: eth13
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 7
                    - 8
                    - 9
            ipmi:
                rack1:
                    - 10
                    - 11
                    - 12
            eth10:
                rack1:
                    - 7
                    - 8
                    - 9
            eth11:
                rack1:
                    - 7
                    - 8
                    - 9
            eth12:
                rack1:
                    - 10
                    - 11
                    - 12
            eth13:
                rack1:
                    - 10
                    - 11
                    - 12
        networks:
            - ext1
            - ext2
            - ext3
            - ext4
            - external1
            - external2
            - openstack-mgmt
            - openstack-stg
            - swift-replication
            - pxe-dhcp
        domain-settings:
            # These settings specify the list of devices that will be used
            # for the rings.  The values can be disk device by path, in which
            # case all the disks under the path will be used, or individual disks
            # can be specified using /dev/sdb style naming.
            account-ring-devices:
                - /dev/disk/by-path/pci-0000:01
            container-ring-devices:
                - /dev/disk/by-path/pci-0000:01
            object-ring-devices:
                - /dev/disk/by-path/pci-0004:01
    swift-proxy:
        hostname: swiftproxy
        userid-ipmi: admin
        password-ipmi: admin
        cobbler-profile: ubuntu-16.04.1-server-ppc64el
        name-interfaces:
            mac-pxe: eth15
            mac-eth10: eth10
            mac-eth11: eth11
            mac-eth12: eth12
            mac-eth13: eth13
        # Each host has one network interface for each of these ports and
        # these port numbers represent the switch port number to which the host
        # interface is cabled.  If a port can be broken out using breakout
        # cables, then this would be specified as '- <port>/<sub-port>'.
        # To add or remove hosts for this node-template you add or remove
        # switch port numbers to these ports.
        ports:
            pxe:
                rack1:
                    - 13
                    - 14
                    - 15
            ipmi:
                rack1:
                    - 16
                    - 17
                    - 18
            eth10:
                rack1:
                    - 13
                    - 14
                    - 15
            eth11:
                rack1:
                    - 13
                    - 14
                    - 15
            eth12:
                rack1:
                    - 16
                    - 17
                    - 18
            eth13:
                rack1:
                    - 16
                    - 17
                    - 18
        networks:
            - ext1
            - ext2
            - ext3
            - ext4
            - external1
            - external2
            - openstack-mgmt
            - openstack-stg
            - pxe-dhcp

software-bootstrap:
    controllers[0]: |
        export GIT_BRANCH=master
        export DEPLOY_CEPH=no
        export DEPLOY_OPSMGR=yes
        # export ANSIBLE_HOST_KEY_CHECKING=False
        URL="https://raw.githubusercontent.com/open-power-ref-design-toolkit/os-services/${GIT_BRANCH}/scripts/bootstrap-solution.sh"
        wget ${URL}
        chmod +x bootstrap-solution.sh
        ./bootstrap-solution.sh

